server:
  port: 80

spring:
  r2dbc:
    username: postgres
    password: root
    url: r2dbc:postgres://localhost:5432/socket_chart
    pool:
      enabled: true

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
